
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
        exclude: "DeepSpeedExamples/"
    -   id: check-yaml
        exclude: "DeepSpeedExamples/"
    -   id: end-of-file-fixer
        exclude: "DeepSpeedExamples/"
        exclude: "docs/CNAME"
    -   id: mixed-line-ending
        exclude: "DeepSpeedExamples/"
        args: [--fix=lf]

-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.29.0
    hooks:
    -   id: yapf
        exclude: "examples/"

-   repo: https://gitlab.com/daverona/pre-commit-cpp
    rev: 0.6.0
    hooks:
    -   id: clang-format  # formatter of C/C++ code based on a style guide: LLVM, Google, Chromium, Mozilla, and WebKit available
        args: []
