name: Create Virtual Environment

runs:
  using: "composite"
  steps:
    - id: update-env
      run: |
        sudo apt-get update && sudo apt-get -y upgrade
        pip install --upgrade pip
        python -m pip install -U virtualenv
      shell: bash
    - id: create-venv
      run: |
        sudo apt-get update && sudo apt-get -y upgrade
        pip install --upgrade pip
        python -m pip install -U virtualenv
        python -m venv unit-test-venv
        source ./unit-test-venv/bin/activate
        pip install --upgrade pip
        echo PATH=$PATH >> $GITHUB_ENV # Make it so venv is inherited for other steps
      shell: bash
    - id: print-env
      run: |
        echo "JobID: $AISC_NODE_INSTANCE_ID"
        which python
        python --version
        if command -v nvidia-smi; then
          nvidia-smi
          which nvcc
          nvcc --version
        else
          rocm-smi --showhw
          which hipcc
          hipcc --version
        fi
      shell: bash
