name: Build DeepSpeed

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: release-env

    steps:
    - uses: actions/checkout@v3
      with:
        ref: "master"

    - id: setup-venv
      uses: ./.github/workflows/setup-venv

    - name: Build DeepSpeed
      run: |
        DS_BUILD_STRING=" " python setup.py sdist