name: nv-lightning-v100

on:
  push:
    branches:
      - 'master'
      - 'staging**'
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: [self-hosted, nvidia, cu111, v100]

    steps:
      - uses: actions/checkout@v2

      - name: set pip
          echo "PIP=$(which pip)" >> $GITHUB_ENV

      - name: environment
        run: |
          nvidia-smi
          which python
          python --version
          which nvcc
          nvcc --version
          sudo ${{ env.PIP }} uninstall --yes torch torchvision
          sudo ${{ env.PIP }} install torch==1.8.2+cu111 torchvision==0.9.2+cu111 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html
          python -c "import torch; print('torch:', torch.__version__, torch)"
          python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
      - name: Install deepspeed
        run: |
          sudo ${{ env.PIP }} uninstall --yes deepspeed
          sudo ${{ env.PIP }} install .[dev,autotuning]
          ds_report
      - name: PyTorch Lightning Tests
        run: |
          if [[ -d ./torch-extensions ]]; then rm -rf ./torch-extensions; fi
          sudo ${{ env.PIP }} uninstall --yes pytorch-lightning
          sudo ${{ env.PIP }} install pytorch-lightning
          sudo ${{ env.PIP }} install "protobuf<4.21.0"
          cd tests
          TORCH_EXTENSIONS_DIR=./torch-extensions pytest --color=yes --durations=0 --verbose lightning/
