name: python

on:
  push:
    branches:
      - 'master'
      - 'staging**'
  pull_request:
    branches:
      '**'

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  vCheck:
    strategy:
      matrix:
        pyVersion: ["3.6", "3.7", "3.8", "3.9", "3.10"]

    runs-on: ubuntu-20.04
    container:
      image: deepspeed/gh-builder:py${{ matrix.pyVersion }}

    steps:
        - uses: actions/checkout@v2

        - name: environment
          run: |
            which python
            python --version
        - name: Install deepspeed
          run: |
            pip3 install .[dev]
        - name: DS Report
          run: |
             ds_report
